namespace lms_test1.Models.DTO.TeacherSubject;

public record TeacherSubjectDTO(
    int Id,
    string TeacherId,
    int SubjectId,    
    double WW1_First,
    double WW2_First,
    double WW3_First,
    double WW4_First,
    double WW5_First,
    double WW6_First,
    double WW7_First,
    double WW8_First,
    double WW9_First,
    double WW10_First,
    double PT1_First,
    double PT2_First,
    double PT3_First,
    double PT4_First,
    double PT5_First,
    double PT6_First,
    double PT7_First,
    double PT8_First,
    double PT9_First,
    double PT10_First,

    double Exam_First,

    double WW1_Second,
    double WW2_Second,
    double WW3_Second,
    double WW4_Second,
    double WW5_Second,
    double WW6_Second,
    double WW7_Second,
    double WW8_Second,
    double WW9_Second,
    double WW10_Second,
    double PT1_Second,
    double PT2_Second,
    double PT3_Second,
    double PT4_Second,
    double PT5_Second,
    double PT6_Second,
    double PT7_Second,
    double PT8_Second,
    double PT9_Second,
    double PT10_Second,
    double Exam_Second
);